@SETLOCAL
@IF NOT DEFINED NODE_PATH (
  @SET "NODE_PATH=C:\Users\27749\Desktop\单词库\部署上线\276762017282\node_modules\.pnpm\browserslist@4.24.5\node_modules\browserslist\node_modules;C:\Users\27749\Desktop\单词库\部署上线\276762017282\node_modules\.pnpm\browserslist@4.24.5\node_modules;C:\Users\27749\Desktop\单词库\部署上线\276762017282\node_modules\.pnpm\node_modules"
) ELSE (
  @SET "NODE_PATH=C:\Users\27749\Desktop\单词库\部署上线\276762017282\node_modules\.pnpm\browserslist@4.24.5\node_modules\browserslist\node_modules;C:\Users\27749\Desktop\单词库\部署上线\276762017282\node_modules\.pnpm\browserslist@4.24.5\node_modules;C:\Users\27749\Desktop\单词库\部署上线\276762017282\node_modules\.pnpm\node_modules;%NODE_PATH%"
)
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\.pnpm\browserslist@4.24.5\node_modules\browserslist\cli.js" %*
) ELSE (
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\.pnpm\browserslist@4.24.5\node_modules\browserslist\cli.js" %*
)
